# Parses config/build.cfg (simple KEY = VALUE lines, '#' comments) and exposes
# each KEY as a CMake variable OTACON_<KEY>. Re-runs if the file changes.
function(otacon_read_build_cfg cfg_path)
  if(NOT EXISTS "${cfg_path}")
    message(FATAL_ERROR "Otacon: build config not found: ${cfg_path}")
  endif()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${cfg_path}")

  file(STRINGS "${cfg_path}" lines)
  foreach(line IN LISTS lines)
    string(STRIP "${line}" line)
    if(line STREQUAL "" OR line MATCHES "^#")
      continue()
    endif()
    if(line MATCHES "^([A-Za-z_][A-Za-z0-9_]*)[ \t]*=[ \t]*(.*)$")
      set(key "${CMAKE_MATCH_1}")
      set(val "${CMAKE_MATCH_2}")
      string(REGEX REPLACE "[ \t]*#.*$" "" val "${val}")
      string(STRIP "${val}" val)
      set("OTACON_${key}" "${val}" PARENT_SCOPE)
      message(STATUS "  build.cfg: ${key} = ${val}")
    endif()
  endforeach()
endfunction()
